spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mobilele?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: never

mobilele:
  remember.me.key: ${REMEMBER_ME_KEY}

open.exchange.rates:
  schema: https
  host: openexchangerates.org
  path: /api/latest.json
  app_id: ${APP_ID}
  symbols: EUR,BGN
  enabled: false

#server:
#  servlet:
#    session:
#      timeout: 30m
